workflows:
  my-workflow:
    name: My workflow name
    labels:
      - QA
      - ${TENANT_NAME}
    instance_type: mac_mini_m1
    environment:
      groups:
        - group_name
      flutter: stable
      xcode: latest
    scripts:
      - wget --help
